### ISSUE TITLE
Installing Gulp in Azure website shows a failure message, but actually installs

### ISSUE THREAD

**Issue by ksaye** [bestander/gulp-deploy-azure-cdn#6]
Step 1.  Install a new Azure WebSite
Step 2. Goto Tools ==> Extensions and add the Gulp extension.
Step 3. See the error message on the top right
![gulpinstallerror](https://cloud.githubusercontent.com/assets/15837044/14052236/9d84334e-f296-11e5-99a2-099e73c9471a.png)
Step 4. Refresh the Extensions screen and see Gulp is installed

**Comment by bestander** [comment]
Hi, @ksaye.

This is not an official Azure repo.
This is just a library that wraps some Azure API.
You'll probably get better support at Microsoft GitHub account.
