### ISSUE TITLE
empty folder in azure blob

### ISSUE THREAD

**Issue by trickydisco78** [bestander/gulp-deploy-azure-cdn#7]
Hi,

I have tried changing all the settings in my gulp file but every time i upload any assets a blank folder is created in azure

![image](https://user-images.githubusercontent.com/3627429/29215592-8b637ca2-7ea3-11e7-9f13-77ebd32dff35.png)

![image](https://user-images.githubusercontent.com/3627429/29215609-992304f2-7ea3-11e7-982a-5649548fc902.png)

this means i can't access it through the cdn endpoint. Not sure why this is happening?

**Comment by bestander** [comment]
No, never happened to me.

**Comment by trickydisco78** [comment]
ah i've cracked it. I never set the destination folder path which meant that I had to have a value in the folder path. I changed this around and it now deploys without a blank folder

![image](https://user-images.githubusercontent.com/3627429/29312775-ddbf7b6e-81ae-11e7-89d0-3f188250492e.png)

**Comment by bestander** [comment]
Nice, great that it works now
